- name: Variables from PLAY level
  hosts: localhost
  vars_files:
    - variables.yaml
  tasks:
  - name: Check Variables
    ansible.builtin.debug:
      msg: "hi im {{Name}}, learning {{Course}}, from {{Institute}}, duration will be {{Time}},"