- name: checking datatypes
  hosts: localhost
  vars:
    NAME: SIVA
    SKILLS:
    - DEVOPS
    - BASH
    - ANSIBLE
    - AWS
    EXPERIENCE:
      AWS: 1
      DEVOPS: 2
      ANSIBLE: 3
    TRAINER: true
  tasks:
  - name: print key value pair
    ansible.builtin.debug:
      msg: "name:: {{NAME}}"

  - name: print list
    ansible.builtin.debug:
      msg: "skills:: {{SKILLS}}"
    
  - name: print map
    ansible.builtin.debug:
      msg: "experience:: {{EXPERIENCE}}"
  
  - name: print boolean
    ansible.builtin.debug:
      msg: "IS HE TRAINER {{TRAINER}}"