- name: conditions
  hosts: localhost
  tasks:
  - name: check roboshop use
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true

  - name: print the 
    ansible.builtin.debug:
      msg: "user output:: is {{user}}"