- name: conditions
  hosts: localhost
  tasks:
  - name: check roboshop user
    ansible.builtin.command: id roboshop
    register: user
    ignore: true

  - name: print the value
    ansible.builtin.debug:
      msg: "user output:: is {{user}}"