- name: printing loops
  hosts: localhost
  tasks:
  - name: printing the given loops
    ansible.builtin.debug:
      msg: "hello {{item}}"
    loop:
    - siva
    - sankar
    - deva
    - mahadeva