[web]
3.91.247.94

[localhost]
localhost

#[localhost:vars]
#Name="siva"
#Course="Devops"
#Institute="joindevops"
#Time="110 hrs"

[catalogue]
4.92.247.94
5.92.247.94

[shipping]
5.82.94.558
5.82.95.258

5.23.32.358
5.23.36.963

[roboshop:children]
web
catalogue
shipping